/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.plan; // 声明包名,该类位于org.apache.calcite.plan包下,是Calcite优化器计划相关的核心包

import org.apache.calcite.rel.RelNode; // 导入RelNode接口,表示关系代数表达式的基础接口,所有关系操作节点都继承自它
import org.apache.calcite.rel.core.RelFactories; // 导入RelFactories类,提供创建各种RelNode的工厂方法的集合
import org.apache.calcite.tools.RelBuilderFactory; // 导入RelBuilderFactory接口,用于创建RelBuilder实例的工厂接口

import com.google.common.collect.ImmutableList; // 导入Google Guava的ImmutableList,提供不可变列表实现

import org.checkerframework.checker.nullness.qual.Nullable; // 导入Checker Framework的Nullable注解,用于标记可空类型
import org.immutables.value.Value; // 导入Immutables库的Value注解,用于自动生成不可变值对象

import java.util.ArrayList; // 导入ArrayList,动态数组实现
import java.util.List; // 导入List接口,表示有序集合
import java.util.Locale; // 导入Locale类,用于本地化相关的操作
import java.util.function.BiConsumer; // 导入BiConsumer函数式接口,表示接受两个参数且无返回值的操作
import java.util.function.Function; // 导入Function函数式接口,表示接受一个参数并返回结果的操作
import java.util.function.Predicate; // 导入Predicate函数式接口,表示接受一个参数并返回布尔值的断言

import static java.util.Objects.requireNonNull; // 静态导入Objects类的requireNonNull方法,用于参数非空校验

/**
 * Rule that is parameterized via a configuration.
 * 通过配置参数化的规则类
 *
 * <p>Eventually (before Calcite version 2.0), this class will replace
 * {@link RelOptRule}. Constructors of {@code RelOptRule} are deprecated, so new
 * rule classes should extend {@code RelRule}, not {@code RelOptRule}.
 * 最终(在Calcite 2.0版本之前),这个类将替代RelOptRule。RelOptRule的构造方法已被弃用,
 * 因此新的规则类应该继承RelRule,而不是RelOptRule。
 *
 * <p>Next, we will deprecate {@code RelOptRule}, so that variables that reference
 * rules will be of type {@code RelRule}.
 * 接下来,我们将弃用RelOptRule,使得引用规则的变量类型为RelRule。
 *
 * <p><b>Guidelines for writing rules</b>
 * <b>编写规则的指南</b>
 *
 * <p>1. If your rule is a sub-class of
 * {@link org.apache.calcite.rel.convert.ConverterRule}
 * and does not need any extra properties,
 * there's no need to create an {@code interface Config} inside your class.
 * In your class, create a constant
 * {@code public static final Config DEFAULT_CONFIG}. Goto step 5.
 * 1. 如果你的规则是ConverterRule的子类并且不需要额外的属性,
 * 那么不需要在你的类中创建interface Config。在你的类中创建一个常量
 * public static final Config DEFAULT_CONFIG。然后跳转到步骤5。
 *
 * <p>2. If your rule is not a sub-class of
 * {@link org.apache.calcite.rel.convert.ConverterRule},
 * create an inner {@code interface Config extends RelRule.Config} and
 * annotate it with {@code @Value.Immutable}. Note, if your inner class
 * is two levels deep (e.g. top-level Rule with Config inside), we recommend
 * you annotate the outer class with {@code @Value.Enclosing} which will
 * instruct the annotation processor to put your generated value class
 * inside a new Immutable outer class. If your rule is three levels deep,
 * the best thing to do is give your class a unique name to avoid any
 * generated code class name overlaps.
 * Implement {@link Config#toRule() toRule} using a {@code default} method:
 * 2. 如果你的规则不是ConverterRule的子类,创建一个内部interface Config extends RelRule.Config
 * 并用@Value.Immutable注解它。注意,如果你的内部类有两层嵌套(例如顶层Rule包含Config),
 * 我们建议你用@Value.Enclosing注解外部类,这将指示注解处理器将生成的值类放在一个新的Immutable外部类中。
 * 如果你的规则有三层嵌套,最好的做法是给你的类一个唯一的名称以避免生成的代码类名冲突。
 * 使用default方法实现Config#toRule():
 *
 * <blockquote>
 * <code>
 * &#x40;Override default CsvProjectTableScanRule toRule() {<br>
 * &nbsp;&nbsp;return new CsvProjectTableScanRule(this);<br>
 * }
 * </code>
 * </blockquote>
 *
 * <p>3. For each configuration property, create a pair of methods in your
 * {@code Config} interface. For example, for a property {@code foo} of type
 * {@code int}, create methods {@code foo} and {@code withFoo}:
 * 3. 对于每个配置属性,在你的Config接口中创建一对方法。例如,对于int类型的属性foo,
 * 创建方法foo和withFoo:
 *
 * <blockquote><pre><code>
 * &#x2f;** Returns foo. *&#x2f;
 * int foo();
 *
 * &#x2f;** Sets {&#x40;link #foo}. *&#x2f;
 * Config withFoo(int x);
 * </code></pre></blockquote>
 *
 * <p>4. In your {@code Config} interface, create a {@code DEFAULT} constant
 * that represents the most typical configuration of your rule. This default
 * will leverage the Immutables class generated by the Annotation Processor
 * based on the annotation you provided above. For example,
 * {@code CsvProjectTableScanRule.Config} has the following:
 * 4. 在你的Config接口中,创建一个DEFAULT常量来表示你的规则的最典型配置。
 * 这个默认配置将利用基于你上面提供的注解由注解处理器生成的Immutables类。
 * 例如,CsvProjectTableScanRule.Config有如下内容:
 *
 * <blockquote><pre><code>
 * Config DEFAULT = ImmutableCsvProjectTableScanRule.Config.builder()
 *     .withOperandSupplier(b0 -&gt;
 *         b0.operand(LogicalProject.class).oneInput(b1 -&gt;
 *             b1.operand(CsvTableScan.class).noInputs()))
 *      .build();
 * </code></pre></blockquote>
 *
 * <p>5. Do not create an {@code INSTANCE} constant inside your rule.
 * Instead, create a named instance of your rule, with default configuration,
 * in a holder class. The holder class must not be a sub-class of
 * {@code RelOptRule} (otherwise cyclic class-loading issues may arise).
 * Generally it will be called <code><i>Xxx</i>Rules</code>, for example
 * {@code CsvRules}. The rule instance is named after your rule, and is based
 * on the default config ({@code Config.DEFAULT}, or {@code DEFAULT_CONFIG} for
 * converter rules):
 * 5. 不要在你的规则内部创建INSTANCE常量。相反,在一个holder类中创建一个具有默认配置的
 * 命名规则实例。holder类不能是RelOptRule的子类(否则可能出现类加载循环问题)。
 * 通常它会被命名为XxxRules,例如CsvRules。规则实例以你的规则命名,并基于默认配置
 * (Config.DEFAULT,对于转换规则是DEFAULT_CONFIG):
 *
 * <blockquote><pre><code>
 * &#x2f;** Rule that matches a {&#x40;code Project} on a
 *  * {&#x40;code CsvTableScan} and pushes down projects if possible. *&#x2f;
 * public static final CsvProjectTableScanRule PROJECT_SCAN =
 *     CsvProjectTableScanRule.Config.DEFAULT.toRule();
 * </code></pre></blockquote>
 *
 * @param <C> Configuration type - 泛型参数C,表示配置类型,必须是RelRule.Config的子类型
 */
public abstract class RelRule<C extends RelRule.Config> extends RelOptRule { // 定义抽象类RelRule,泛型C必须是RelRule.Config的子类型,继承自RelOptRule
  public final C config; // 声明final类型的配置对象config,存储规则的配置信息,final表示初始化后不可修改

  /** Creates a RelRule. */
  protected RelRule(C config) { // 受保护的构造方法,接受一个配置对象config作为参数
    super(OperandBuilderImpl.operand(config.operandSupplier()), // 调用父类RelOptRule的构造方法,第一个参数是通过OperandBuilderImpl.operand方法根据配置的operandSupplier创建的操作数
        config.relBuilderFactory(), // 第二个参数是配置中的关系构建器工厂,用于创建RelBuilder实例
        config.description()); // 第三个参数是配置中的规则描述信息
    this.config = config; // 将传入的配置对象赋值给成员变量config
  } // 构造方法结束

  /** Rule configuration. */
  public interface Config { // 定义公共接口Config,用于配置规则,所有规则配置都必须实现这个接口

    /** Creates a rule that uses this configuration. Sub-class must override. */
    RelOptRule toRule(); // 创建一个使用此配置的规则,子类必须重写此方法,返回具体的RelOptRule实例

    /** Casts this configuration to another type, usually a sub-class. */
    default <T extends Object> T as(Class<T> class_) { // 默认方法,将当前配置转换为另一种类型,通常是子类
      if (class_.isAssignableFrom(this.getClass())) { // 检查目标类型class_是否可以赋值给当前配置的类型
        return class_.cast(this); // 如果可以,执行类型转换并返回
      } else { // 如果不能转换
        throw new UnsupportedOperationException( // 抛出不支持的操作异常
            String.format(Locale.ROOT, // 使用ROOT语言环境格式化错误消息
                "The current config of type %s is not an instance of %s.", // 错误消息模板
                this.getClass(), // 当前配置的类型
                class_)); // 目标类型
      }
    }

    /** The factory that is used to create a
     * {@link org.apache.calcite.tools.RelBuilder} during rule invocations. */
    @Value.Default default RelBuilderFactory relBuilderFactory() { // 定义默认的关系构建器工厂方法,用于在规则调用期间创建RelBuilder
      return RelFactories.LOGICAL_BUILDER; // 返回逻辑构建器工厂作为默认值
    }

    /** Sets {@link #relBuilderFactory()}. */
    Config withRelBuilderFactory(RelBuilderFactory factory); // 设置关系构建器工厂的方法,接收RelBuilderFactory参数,返回Config实例以支持链式调用

    /** Description of the rule instance. */
    // CALCITE-4831: remove the second nullable annotation once immutables/#1261 is fixed
    @javax.annotation.Nullable @Nullable String description(); // 规则实例的描述信息,可以为null,使用两个Nullable注解是为了兼容性(注释说明在immutables/#1261修复后移除第二个注解)

    /** Sets {@link #description()}. */
    Config withDescription(@Nullable String description); // 设置规则描述的方法,接收可空的String参数,返回Config实例以支持链式调用

    /** Creates the operands for the rule instance. */
    @Value.Default default OperandTransform operandSupplier() { // 定义默认的操作数提供者方法,用于创建规则实例的操作数
      return s -> { // 返回一个lambda表达式,接受OperandBuilder参数s
        throw new IllegalArgumentException("Rules must have at least one " // 抛出非法参数异常
            + "operand. Call Config.withOperandSupplier to specify them."); // 错误消息提示规则必须至少有一个操作数,需要调用withOperandSupplier方法来指定
      }; // lambda表达式结束

    }

    /** Sets {@link #operandSupplier()}. */
    Config withOperandSupplier(OperandTransform transform); // 设置操作数提供者的方法,接收OperandTransform参数,返回Config实例以支持链式调用
  } // Config接口定义结束

  /** Function that creates an operand.
   * 用于创建操作数的函数接口
   *
   * @see Config#withOperandSupplier(OperandTransform) - 参见Config.withOperandSupplier方法 */
  @FunctionalInterface // 标记为函数式接口,只有一个抽象方法
  public interface OperandTransform extends Function<OperandBuilder, Done> { // 定义OperandTransform接口,继承自Function<OperandBuilder, Done>,表示一个接受OperandBuilder并返回Done的函数
  } // OperandTransform接口定义结束,这是一个函数式接口,用于构建规则的操作数

  /** Callback to create an operand.
   * 用于创建操作数的回调接口
   *
   * @see OperandTransform - 参见OperandTransform接口 */
  public interface OperandBuilder { // 定义OperandBuilder接口,提供构建操作数的方法
    /** Starts building an operand by specifying its class.
     * 通过指定类来开始构建操作数
     * Call further methods on the returned {@link OperandDetailBuilder} to
     * complete the operand.
     * 调用返回的OperandDetailBuilder上的其他方法来完成操作数的构建
     */
    <R extends RelNode> OperandDetailBuilder<R> operand(Class<R> relClass); // 泛型方法,接受一个RelNode子类的Class对象,返回OperandDetailBuilder用于详细构建操作数

    /** Supplies an operand that has been built manually.
     * 提供一个手动构建的操作数 */
    Done exactly(RelOptRuleOperand operand); // 接受一个已构建好的RelOptRuleOperand对象,返回Done表示操作数已完成
  } // OperandBuilder接口定义结束

  /** Indicates that an operand is complete.
   * 表示操作数构建完成的标记接口
   *
   * @see OperandTransform - 参见OperandTransform接口 */
  public interface Done { // 定义Done接口,这是一个标记接口,用于表示操作数构建完成
  } // Done接口定义结束,不包含任何方法,仅作为类型标记使用

  /** Add details about an operand, such as its inputs.
   * 添加关于操作数的详细信息,例如其输入
   *
   * @param <R> Type of relational expression - 泛型参数R,表示关系表达式的类型,必须是RelNode的子类型 */
  public interface OperandDetailBuilder<R extends RelNode> { // 定义OperandDetailBuilder接口,用于添加操作数的详细信息,泛型R必须是RelNode的子类型
    /** Sets a trait of this operand.
     * 设置此操作数的特征(trait) */
    OperandDetailBuilder<R> trait(RelTrait trait); // 设置操作数的特征,接收RelTrait参数,返回当前Builder实例以支持链式调用

    /** Sets the predicate of this operand.
     * 设置此操作数的谓词(predicate) */
    OperandDetailBuilder<R> predicate(Predicate<? super R> predicate); // 设置操作数的匹配谓词,接收一个Predicate参数,用于过滤匹配的关系表达式,返回当前Builder实例以支持链式调用

    /** Indicates that this operand has a single input.
     * 表示此操作数有一个输入 */
    Done oneInput(OperandTransform transform); // 指定操作数有一个输入,接收OperandTransform参数来构建输入操作数,返回Done表示构建完成

    /** Indicates that this operand has several inputs.
     * 表示此操作数有多个输入(有序) */
    Done inputs(OperandTransform... transforms); // 指定操作数有多个输入,接收可变参数的OperandTransform数组来构建多个输入操作数,返回Done表示构建完成

    /** Indicates that this operand has several inputs, unordered.
     * 表示此操作数有多个输入(无序) */
    Done unorderedInputs(OperandTransform... transforms); // 指定操作数有多个无序输入,接收可变参数的OperandTransform数组来构建多个输入操作数,返回Done表示构建完成

    /** Indicates that this operand takes any number or type of inputs.
     * 表示此操作数接受任意数量或类型的输入 */
    Done anyInputs(); // 指定操作数可以接受任意数量或类型的输入,返回Done表示构建完成

    /** Indicates that this operand takes no inputs.
     * 表示此操作数没有输入(叶子节点) */
    Done noInputs(); // 指定操作数没有输入,即它是叶子节点,返回Done表示构建完成

    /** Indicates that this operand converts a relational expression to
     * another trait.
     * 表示此操作数将关系表达式转换为另一个特征 */
    Done convert(RelTrait in); // 指定操作数是一个转换操作,将关系表达式转换为指定的特征,接收RelTrait参数,返回Done表示构建完成
  } // OperandDetailBuilder接口定义结束

  /** Implementation of {@link OperandBuilder}.
 * OperandBuilder接口的实现类 */
  private static class OperandBuilderImpl implements OperandBuilder { // 定义私有静态类OperandBuilderImpl,实现OperandBuilder接口
    final List<RelOptRuleOperand> operands = new ArrayList<>(); // 声明final类型的操作数列表operands,使用ArrayList初始化,存储构建的操作数

    static RelOptRuleOperand operand(OperandTransform transform) { // 静态方法,根据转换函数创建操作数
      final OperandBuilderImpl b = new OperandBuilderImpl(); // 创建OperandBuilderImpl实例
      requireNonNull(transform.apply(b), "done"); // 调用转换函数应用到此builder,要求结果非空,否则抛出NullPointerException
      if (b.operands.size() != 1) { // 检查操作数列表的大小是否为1
        throw new IllegalArgumentException("operand supplier must call one of " // 如果不是1,抛出非法参数异常
            + "the following methods: operand or exactly"); // 错误消息提示必须调用operand或exactly方法之一
      }
      return b.operands.get(0); // 返回操作数列表中的第一个(也是唯一的)操作数
    }

    @Override public <R extends RelNode> OperandDetailBuilder<R> operand(Class<R> relClass) { // 重写operand方法,开始构建一个操作数
      return new OperandDetailBuilderImpl<>(this, relClass); // 创建并返回OperandDetailBuilderImpl实例,传入当前builder和关系表达式类
    }

    @Override public Done exactly(RelOptRuleOperand operand) { // 重写exactly方法,直接提供一个已构建好的操作数
      operands.add(operand); // 将操作数添加到操作数列表中
      return DoneImpl.INSTANCE; // 返回Done的单例实例,表示操作数已完成
    }
  } // OperandBuilderImpl类定义结束

  /** Implementation of {@link OperandDetailBuilder}.
 * OperandDetailBuilder接口的实现类
 *
 * @param <R> Type of relational expression - 泛型参数R,表示关系表达式的类型,必须是RelNode的子类型 */
  private static class OperandDetailBuilderImpl<R extends RelNode> // 定义私有静态类OperandDetailBuilderImpl,实现OperandDetailBuilder接口
      implements OperandDetailBuilder<R> { // 实现OperandDetailBuilder接口,泛型R必须是RelNode的子类型
    private final OperandBuilderImpl parent; // 父构建器,用于将构建好的操作数添加到父构建器的操作数列表中
    private final Class<R> relClass; // 关系表达式的类类型,用于匹配特定类型的RelNode
    final OperandBuilderImpl inputBuilder = new OperandBuilderImpl(); // 输入构建器,用于构建此操作数的子操作数
    private @Nullable RelTrait trait; // 操作数的特征(trait),可以为null,用于匹配具有特定特征的关系表达式
    private Predicate<? super R> predicate = r -> true; // 匹配谓词,默认总是返回true,表示不进行额外过滤

    OperandDetailBuilderImpl(OperandBuilderImpl parent, Class<R> relClass) { // 构造方法,初始化操作数详细构建器
      this.parent = requireNonNull(parent, "parent"); // 设置父构建器,要求非空
      this.relClass = requireNonNull(relClass, "relClass"); // 设置关系表达式类,要求非空
    }

    @Override public OperandDetailBuilderImpl<R> trait(RelTrait trait) { // 重写trait方法,设置操作数的特征
      this.trait = requireNonNull(trait, "trait"); // 设置特征值,要求非空
      return this; // 返回当前实例以支持链式调用
    }

    @Override public OperandDetailBuilderImpl<R> predicate(Predicate<? super R> predicate) { // 重写predicate方法,设置操作数的匹配谓词
      this.predicate = predicate; // 设置谓词,用于过滤匹配的关系表达式
      return this; // 返回当前实例以支持链式调用
    }

    /** Indicates that there are no more inputs.
     * 表示没有更多输入,完成操作数构建 */
    Done done(RelOptRuleOperandChildPolicy childPolicy) { // 完成操作数构建的内部方法
      parent.operands.add( // 将构建好的操作数添加到父构建器的操作数列表中
          new RelOptRuleOperand(relClass, trait, predicate, childPolicy, // 创建RelOptRuleOperand对象,指定关系类、特征、谓词、子操作数策略
              ImmutableList.copyOf(inputBuilder.operands))); // 将输入构建器的操作数列表转换为不可变列表
      return DoneImpl.INSTANCE; // 返回Done的单例实例,表示操作数已完成
    }

    @Override public Done convert(RelTrait in) { // 重写convert方法,创建一个转换操作数
      parent.operands.add( // 将转换操作数添加到父构建器的操作数列表中
          new ConverterRelOptRuleOperand(relClass, in, predicate)); // 创建ConverterRelOptRuleOperand对象,表示将关系表达式转换为指定特征
      return DoneImpl.INSTANCE; // 返回Done的单例实例,表示操作数已完成
    }

    @Override public Done noInputs() { // 重写noInputs方法,指定操作数没有输入(叶子节点)
      return done(RelOptRuleOperandChildPolicy.LEAF); // 调用done方法,使用LEAF策略表示叶子节点
    }

    @Override public Done anyInputs() { // 重写anyInputs方法,指定操作数接受任意输入
      return done(RelOptRuleOperandChildPolicy.ANY); // 调用done方法,使用ANY策略表示接受任意输入
    }

    @Override public Done oneInput(OperandTransform transform) { // 重写oneInput方法,指定操作数有一个输入
      final Done done = transform.apply(inputBuilder); // 应用转换函数到输入构建器,构建输入操作数
      requireNonNull(done, "done"); // 确保返回的Done对象非空
      return done(RelOptRuleOperandChildPolicy.SOME); // 调用done方法,使用SOME策略表示有特定数量的输入
    }

    @Override public Done inputs(OperandTransform... transforms) { // 重写inputs方法,指定操作数有多个输入(有序)
      for (OperandTransform transform : transforms) { // 遍历所有转换函数
        final Done done = transform.apply(inputBuilder); // 对每个转换函数,应用到输入构建器构建输入操作数
        requireNonNull(done, "done"); // 确保返回的Done对象非空
      }
      return done(RelOptRuleOperandChildPolicy.SOME); // 调用done方法,使用SOME策略表示有特定数量的输入
    }

    @Override public Done unorderedInputs(OperandTransform... transforms) { // 重写unorderedInputs方法,指定操作数有多个输入(无序)
      for (OperandTransform transform : transforms) { // 遍历所有转换函数
        final Done done = transform.apply(inputBuilder); // 对每个转换函数,应用到输入构建器构建输入操作数
        requireNonNull(done, "done"); // 确保返回的Done对象非空
      }
      return done(RelOptRuleOperandChildPolicy.UNORDERED); // 调用done方法,使用UNORDERED策略表示有多个无序输入
    }
  } // OperandDetailBuilderImpl类定义结束

  /** Singleton instance of {@link Done}.
 * Done接口的单例实现 */
  private enum DoneImpl implements Done { // 定义私有枚举DoneImpl,实现Done接口,作为单例使用
    INSTANCE // 定义唯一的枚举实例INSTANCE,表示操作数构建完成
  } // DoneImpl枚举定义结束

  /** Callback interface that helps you avoid creating sub-classes of
   * {@link RelRule} that differ only in implementations of
   * {@link #onMatch(RelOptRuleCall)} method.
   * 回调接口,帮助你避免创建仅onMatch方法实现不同的RelRule子类
   * 这个接口允许你将规则匹配的处理逻辑从规则类中分离出来,
   * 通过函数式编程的方式定义处理逻辑,而不需要创建多个子类
   *
   * @param <R> Rule type - 泛型参数R,表示规则类型,必须是RelOptRule的子类型 */
  public interface MatchHandler<R extends RelOptRule> // 定义公共接口MatchHandler,用于处理规则匹配
      extends BiConsumer<R, RelOptRuleCall> { // 继承自BiConsumer<R, RelOptRuleCall>,表示接受规则和规则调用两个参数且无返回值的操作
  } // MatchHandler接口定义结束
} // RelRule类定义结束
