/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.plan.volcano;

import org.apache.calcite.plan.DeriveMode;
import org.apache.calcite.plan.RelOptCost;
import org.apache.calcite.plan.RelTraitSet;
import org.apache.calcite.rel.PhysicalNode;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.rel.convert.ConverterRule;
import org.apache.calcite.util.Pair;
import org.apache.calcite.util.trace.CalciteTrace;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Stack;
import java.util.function.Predicate;

import static java.util.Objects.requireNonNull;

/**
 * TopDownRuleDriver: 自顶向下规则驱动器，采用自顶向下的方式应用转换规则
 * 类的作用：作为VolcanoPlanner的核心驱动器，负责按照自顶向下的顺序执行优化规则
 * 核心功能：
 * 1. 通过任务队列管理优化过程，确保规则应用的顺序性
 * 2. 实现空间剪枝，避免不必要的规则应用
 * 3. 支持规则互斥性检查，提高优化效率
 * 4. 使用任务栈管理待执行的优化任务
 *
 * 设计理念：
 * - 采用任务驱动的方式，每个Task代表一个待执行的工作单元
 * - 任务可以是应用规则、优化RelSubset、探索输入等
 * - 通过GeneratorTask回调机制处理新生成的RelNode
 * - 支持物理节点的trait推导和属性传递
 *
 * <p>This implementation uses tasks to manage rule matches.
 * A Task is a piece of work to be executed, it may apply some rules
 * or schedule other tasks.
 */
@SuppressWarnings("JdkObsolete")
class TopDownRuleDriver implements RuleDriver {

  private static final Logger LOGGER = CalciteTrace.getPlannerTaskTracer(); // 日志记录器，用于跟踪规划任务执行过程

  private final VolcanoPlanner planner; // Volcano优化器引用，提供核心优化功能

  /**
   * The rule queue designed for top-down rule applying.
   * 规则队列：专门为自顶向下规则应用设计，存储待应用的规则匹配
   */
  private final TopDownRuleQueue ruleQueue; // 自顶向下规则队列，管理待应用的规则匹配

  /**
   * All tasks waiting for execution.
   * 任务栈：存储所有等待执行的任务，使用栈结构实现深度优先执行顺序
   */
  private final Stack<Task> tasks = new Stack<>(); // TODO: replace with Deque // 待执行任务栈，使用深度优先策略

  /**
   * A task that is currently applying and may generate new RelNode.
   * It provides a callback to schedule tasks for new RelNodes that
   * are registered during task performing.
   * 当前正在执行的任务：可能生成新的RelNode，提供回调机制为新生成的节点调度任务
   */
  private @Nullable GeneratorTask applying = null; // 当前正在执行的任务，可能为null

  /**
   * RelNodes that are generated by {@link org.apache.calcite.rel.PhysicalNode#passThrough}
   * or {@link org.apache.calcite.rel.PhysicalNode#derive}. These nodes will not take part
   * in another passThrough or derive.
   * 传递缓存：存储通过passThrough或derive方法生成的RelNode，避免重复生成
   */
  private final Set<RelNode> passThroughCache = new HashSet<>(); // 已传递节点缓存，防止重复传递

  //~ Constructors -----------------------------------------------------------

  TopDownRuleDriver(VolcanoPlanner planner) { // 构造方法：初始化自顶向下规则驱动器
    this.planner = planner; // 保存优化器引用
    ruleQueue = new TopDownRuleQueue(planner); // 创建自顶向下规则队列，传入优化器引用
  }

  //~ Methods ----------------------------------------------------------------

  @Override public void drive() { // drive方法：驱动优化过程的主循环，执行所有待处理的任务
    TaskDescriptor description = new TaskDescriptor(); // 创建任务描述器，用于日志记录

    // Starting from the root's OptimizeGroup task.
    // 从根节点的OptimizeGroup任务开始，初始化任务栈
    tasks.push(
        new OptimizeGroup(
            requireNonNull(planner.root, "planner.root"), // 获取根RelSubset，确保不为null
            planner.infCost)); // 使用无限成本作为初始上界

    // Ensure materialized view roots get explored.
    // Note that implementation rules or enforcement rules are not applied
    // unless the mv is matched.
    exploreMaterializationRoots(); // 确保物化视图根节点被探索，除非物化视图匹配否则不应用实现规则或强制规则

    try {
      // Iterates until the root is fully optimized.
      // 主循环：直到任务栈为空，即所有任务都执行完毕
      while (!tasks.isEmpty()) { // 检查是否还有待执行的任务
        Task task = tasks.pop(); // 从栈顶弹出一个任务（深度优先）
        description.log(task); // 记录任务执行日志
        task.perform(); // 执行任务
      }
    } catch (VolcanoTimeoutException ex) { // 捕获超时异常
      LOGGER.warn("Volcano planning times out, cancels the subsequent optimization."); // 记录警告日志
    }
  }

  private void exploreMaterializationRoots() { // exploreMaterializationRoots方法：探索所有物化视图的根节点
    for (RelSubset extraRoot : planner.explorationRoots) { // 遍历所有探索根节点（物化视图）
      RelSet rootSet = VolcanoPlanner.equivRoot(extraRoot.set); // 获取等价关系的根集合
      RelSubset root = requireNonNull(planner.root, "planner.root"); // 获取主优化器根节点
      if (rootSet == root.set) { // 如果物化视图的根集合与主根集合相同
        continue; // 跳过，避免重复优化
      }
      for (RelNode rel : extraRoot.set.rels) { // 遍历物化视图集合中的所有RelNode
        if (planner.isLogical(rel)) { // 如果是逻辑节点
          tasks.push(new OptimizeMExpr(rel, extraRoot, true)); // 创建探索模式下的优化任务并推入栈
        }
      }
    }
  }

  @Override public TopDownRuleQueue getRuleQueue() { // getRuleQueue方法：获取规则队列
    return ruleQueue; // 返回自顶向下规则队列
  }

  @Override public void clear() { // clear方法：清理驱动器状态，重置所有内部数据结构
    ruleQueue.clear(); // 清空规则队列
    tasks.clear(); // 清空任务栈
    passThroughCache.clear(); // 清空传递缓存
    applying = null; // 重置当前执行任务
  }

  /** Procedure. */
  private interface Procedure { // Procedure接口：过程式任务接口，定义无参无返回值的执行方法
    void exec(); // exec方法：执行过程
  }

  private void applyGenerator(@Nullable GeneratorTask task, Procedure proc) { // applyGenerator方法：应用生成器任务，设置当前执行任务并执行过程
    GeneratorTask applying = this.applying; // 保存当前执行任务
    this.applying = task; // 设置新的生成器任务作为当前执行任务
    try {
      proc.exec(); // 执行过程
    } finally {
      this.applying = applying; // 恢复之前的执行任务
    }
  }

  @Override public void onSetMerged(RelSet set) { // onSetMerged方法：当RelSet合并时的回调处理
    // When RelSets get merged, an optimized group may get extra opportunities.
    // Clear the OPTIMIZED state for the RelSubsets and all their ancestors,
    // so that they will be optimized again.
    // 当RelSet合并时，已优化的组可能获得额外的优化机会
    // 清除RelSubsets及其所有祖先的OPTIMIZED状态，使它们可以重新优化
    applyGenerator(null, () -> clearProcessed(set)); // 应用生成器任务清除已处理状态
  }

  private void clearProcessed(RelSet set) { // clearProcessed方法：递归清除RelSet及其祖先的已处理状态
    boolean explored = set.exploringState != null; // 检查集合是否处于探索状态
    set.exploringState = null; // 清除探索状态

    for (RelSubset subset : set.subsets) { // 遍历集合中的所有子集
      if (subset.resetTaskState() || explored) { // 如果重置任务状态成功或之前处于探索状态
        Collection<RelNode> parentRels = subset.getParentRels(); // 获取所有父RelNode
        for (RelNode parentRel : parentRels) { // 遍历父RelNode
          RelSet parentRelSet =
              requireNonNull(planner.getSet(parentRel), () -> "no set found for " + parentRel); // 获取父RelNode所属的集合
          clearProcessed(parentRelSet); // 递归清除父集合的处理状态
        }
        if (subset == planner.root) { // 如果是根子集
          tasks.push(new OptimizeGroup(subset, planner.infCost)); // 重新调度根子集的优化任务
        }
      }
    }
  }

  // A callback invoked when a RelNode is going to be added into a RelSubset,
  // either by Register or Reregister. The task driver should schedule tasks
  // for the new nodes.
  // 回调方法：当RelNode将要添加到RelSubset时触发（通过Register或Reregister）
  // 任务驱动器应该为新节点调度任务
  @Override public void onProduce(RelNode node, RelSubset subset) { // onProduce方法：处理新产生的RelNode

    // If the RelNode is added to another RelSubset, just ignore it.
    // It should be scheduled in the later OptimizeGroup task.
    // 如果RelNode被添加到另一个RelSubset，忽略它
    // 它应该在后续的OptimizeGroup任务中调度
    if (applying == null || subset.set
        != VolcanoPlanner.equivRoot(applying.group().set)) { // 检查是否在当前任务组内
      return; // 不在当前组内，直接返回
    }

    // Extra callback from each task.
    // 每个任务的额外回调
    if (!requireNonNull(applying, "applying").onProduce(node)) { // 调用当前任务的onProduce回调
      return; // 如果回调返回false，不继续处理
    }

    if (!planner.isLogical(node)) { // 如果是物理节点
      // For a physical node, schedule tasks to optimize its inputs.
      // The upper bound depends on all optimizing RelSubsets that this RelNode belongs to.
      // If there are optimizing subsets that come from the same RelSet,
      // invoke the passThrough method to generate a candidate for that Subset.
      // 对于物理节点，调度任务优化其输入
      // 上界取决于此RelNode所属的所有正在优化的RelSubset
      // 如果有来自同一RelSet的正在优化的子集，调用passThrough方法为该子集生成候选
      RelSubset optimizingGroup = null; // 正在优化的组
      boolean canPassThrough = node instanceof PhysicalNode
          && !passThroughCache.contains(node); // 检查是否可以传递（是物理节点且不在缓存中）
      if (!canPassThrough && subset.taskState != null) { // 如果不能传递且有任务状态
        optimizingGroup = subset; // 使用当前子集作为优化组
      } else { // 可以传递或没有任务状态
        RelOptCost upperBound = planner.zeroCost; // 初始化上界为零成本
        RelSet set = subset.getSet(); // 获取集合
        List<RelSubset> subsetsToPassThrough = new ArrayList<>(); // 待传递的子集列表
        for (RelSubset otherSubset : set.subsets) { // 遍历集合中的所有子集
          if (!otherSubset.isRequired() || otherSubset != planner.root
              && otherSubset.taskState != RelSubset.OptimizeState.OPTIMIZING) { // 如果不是必需的或不是正在优化的根子集
            continue; // 跳过
          }
          if (node.getTraitSet().satisfies(otherSubset.getTraitSet())) { // 如果节点的trait满足子集的trait
            if (upperBound.isLt(otherSubset.upperBound)) { // 如果当前上界小于子集的上界
              upperBound = otherSubset.upperBound; // 更新上界
              optimizingGroup = otherSubset; // 更新优化组
            }
          } else if (canPassThrough) { // 如果可以传递且trait不满足
            subsetsToPassThrough.add(otherSubset); // 添加到待传递列表
          }
        }
        for (RelSubset otherSubset : subsetsToPassThrough) { // 遍历待传递的子集
          Task task = getOptimizeInputTask(node, otherSubset); // 获取优化输入任务
          if (task != null) { // 如果任务不为空
            tasks.push(task); // 推入任务栈
          }
        }
      }
      if (optimizingGroup == null) { // 如果没有找到优化组
        return; // 直接返回
      }
      Task task = getOptimizeInputTask(node, optimizingGroup); // 获取优化输入任务
      if (task != null) { // 如果任务不为空
        tasks.push(task); // 推入任务栈
      }
    } else { // 如果是逻辑节点
      boolean optimizing = subset.set.subsets.stream() // 检查集合中是否有正在优化的子集
          .anyMatch(s -> s.taskState == RelSubset.OptimizeState.OPTIMIZING);
      GeneratorTask applying = requireNonNull(this.applying, "this.applying"); // 获取当前执行任务
      tasks.push(
          new OptimizeMExpr(node, applying.group(), // 创建优化MExpr任务
              applying.exploring() && !optimizing)); // 探索模式取决于任务状态
    }
  }

  //~ Inner Classes ----------------------------------------------------------

  /**
   * Base class for planner task.
   * Task接口：规划器任务的基础接口，定义所有任务的通用行为
   */
  private interface Task { // Task接口：表示可执行的任务
    void perform(); // perform方法：执行任务的具体逻辑
    void describe(TaskDescriptor desc); // describe方法：描述任务信息，用于日志记录
  }

  /**
   * A class for task logging.
   * TaskDescriptor类：任务描述器，用于生成任务执行的日志信息
   */
  private static class TaskDescriptor { // TaskDescriptor类：任务日志记录器
    private boolean first = true; // 标记是否是第一个参数
    private final StringBuilder builder = new StringBuilder(); // 字符串构建器，用于构建日志消息

    void log(Task task) { // log方法：记录任务执行日志
      if (!LOGGER.isDebugEnabled()) { // 如果不是调试级别
        return; // 不记录日志
      }
      first = true; // 重置为第一个参数
      builder.setLength(0); // 清空构建器
      builder.append("Execute task: ").append(task.getClass().getSimpleName()); // 添加任务类名
      task.describe(this); // 让任务描述自身
      if (!first) { // 如果有参数
        builder.append(")"); // 添加闭合括号
      }

      LOGGER.debug(builder.toString()); // 输出调试日志
    }

    TaskDescriptor item(String name, Object value) { // item方法：添加任务描述项
      if (first) { // 如果是第一个参数
        first = false; // 标记为非第一个
        builder.append("("); // 添加左括号
      } else { // 如果不是第一个参数
        builder.append(", "); // 添加逗号分隔符
      }
      builder.append(name).append("=").append(value); // 添加参数名和值
      return this; // 返回自身以支持链式调用
    }
  }

  /** Task for generator. */
  private interface GeneratorTask extends Task { // GeneratorTask接口：生成器任务接口，可以生成新的RelNode
    RelSubset group(); // group方法：返回任务所属的RelSubset组
    boolean exploring(); // exploring方法：返回是否处于探索模式
    default boolean onProduce(RelNode node) { // onProduce方法：当产生新RelNode时的回调，默认返回true表示继续处理
      return true;
    }
  }

  /**
   * Optimizes a RelSubset.
   * It schedules optimization tasks for RelNodes in the RelSet.
   * OptimizeGroup类：优化RelSubset的任务，为RelSet中的RelNode调度优化任务
   */
  private class OptimizeGroup implements Task { // OptimizeGroup类：RelSubset优化任务
    private final RelSubset group; // 要优化的RelSubset组
    private final RelOptCost upperBound; // 优化上界，用于剪枝

    OptimizeGroup(RelSubset group, RelOptCost upperBound) { // 构造方法：创建优化组任务
      this.group = group; // 保存RelSubset
      this.upperBound = upperBound; // 保存上界
    }

    @Override public void perform() { // perform方法：执行优化组任务
      RelOptCost winner = group.getWinnerCost(); // 获取已有最优成本
      if (winner != null) { // 如果已经有最优解
        return; // 无需继续优化
      }

      if (group.taskState != null && upperBound.isLe(group.upperBound)) { // 如果之前优化失败或存在循环
        // Either this group failed to optimize before or it is a ring.
        // 要么这个组之前优化失败，要么存在循环
        return; // 直接返回
      }

      group.startOptimize(upperBound); // 开始优化，设置上界

      // Cannot decide an actual lower bound before MExpr are fully explored.
      // So delay the lower bound check.
      // 在MExpr完全探索之前无法确定实际下界
      // 因此延迟下界检查

      // A gate keeper to update context.
      // 添加守门任务，用于更新上下文
      tasks.push(new GroupOptimized(group)); // 将组优化完成任务推入栈

      // Optimize mExprs in group.
      // 优化组中的mExpr
      List<RelNode> physicals = new ArrayList<>(); // 物理节点列表
      for (RelNode rel : group.set.rels) { // 遍历集合中的所有RelNode
        if (planner.isLogical(rel)) { // 如果是逻辑节点
          tasks.push(new OptimizeMExpr(rel, group, false)); // 创建优化MExpr任务（非探索模式）
        } else if (rel.isEnforcer()) { // 如果是强制节点
          // Enforcers have lower priority than other physical nodes.
          // 强制节点优先级低于其他物理节点
          physicals.add(0, rel); // 添加到列表开头
        } else { // 普通物理节点
          physicals.add(rel); // 添加到列表末尾
        }
      }
      // Always apply O_INPUTS first so as to get a valid upper bound.
      // 总是先应用O_INPUTS以获得有效的上界
      for (RelNode rel : physicals) { // 遍历物理节点
        Task task = getOptimizeInputTask(rel, group); // 获取优化输入任务
        if (task != null) { // 如果任务不为空
          tasks.add(task); // 添加到任务栈
        }
      }
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("group", group).item("upperBound", upperBound); // 添加组和上界信息
    }
  }

  /**
   * Marks the RelSubset optimized.
   * When GroupOptimized returns, the group is either fully
   * optimized and has a winner or failed to be optimized.
   * GroupOptimized类：标记RelSubset已优化的任务
   * 当GroupOptimized返回时，组要么完全优化并有最优解，要么优化失败
   */
  private static class GroupOptimized implements Task { // GroupOptimized类：组优化完成标记任务
    private final RelSubset group; // 要标记的RelSubset组

    GroupOptimized(RelSubset group) { // 构造方法：创建组优化完成任务
      this.group = group; // 保存RelSubset
    }

    @Override public void perform() { // perform方法：执行标记任务
      group.setOptimized(); // 标记组为已优化
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("group", group) // 添加组信息
          .item("upperBound", group.upperBound); // 添加上界信息
    }
  }

  /**
   * Optimizes a logical node, including exploring its input and applying rules for it.
   * OptimizeMExpr类：优化逻辑节点的任务，包括探索其输入和应用规则
   */
  private class OptimizeMExpr implements Task { // OptimizeMExpr类：逻辑节点优化任务
    private final RelNode mExpr; // 要优化的逻辑表达式（RelNode）
    private final RelSubset group; // 所属的RelSubset组

    // When true, only apply transformation rules for mExpr.
    // 当为true时，只应用转换规则给mExpr
    private final boolean explore; // 探索模式标志

    OptimizeMExpr(RelNode mExpr, // 构造方法：创建优化MExpr任务
        RelSubset group, boolean explore) {
      this.mExpr = mExpr; // 保存RelNode
      this.group = group; // 保存RelSubset
      this.explore = explore; // 保存探索模式标志
    }

    @Override public void perform() { // perform方法：执行优化任务
      if (explore && group.isExplored()) { // 如果是探索模式且组已探索
        return; // 无需重复探索
      }
      // 1. explore input.
      // 2. apply other rules.
      // 1. 探索输入
      // 2. 应用其他规则
      tasks.push(new ApplyRules(mExpr, group, explore)); // 推入应用规则任务
      for (int i = mExpr.getInputs().size() - 1; i >= 0; --i) { // 逆序遍历输入（保证顺序执行）
        tasks.push(new ExploreInput(mExpr, i)); // 推入探索输入任务
      }
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", mExpr).item("explore", explore); // 添加mExpr和探索模式信息
    }
  }

  /**
   * Ensures that ExploreInputs are working on the correct input group.
   * Currently, a RelNode's input may change since Calcite may merge RelSets.
   * EnsureGroupExplored类：确保ExploreInputs工作在正确的输入组上
   * 目前RelNode的输入可能会改变，因为Calcite可能合并RelSets
   */
  private class EnsureGroupExplored implements Task { // EnsureGroupExplored类：确保组探索任务

    private final RelSubset input; // 输入RelSubset
    private final RelNode parent; // 父RelNode
    private final int inputOrdinal; // 输入序号

    EnsureGroupExplored(RelSubset input, RelNode parent, int inputOrdinal) { // 构造方法：创建确保组探索任务
      this.input = input; // 保存输入RelSubset
      this.parent = parent; // 保存父RelNode
      this.inputOrdinal = inputOrdinal; // 保存输入序号
    }

    @Override public void perform() { // perform方法：执行确保任务
      if (parent.getInput(inputOrdinal) != input) { // 如果父节点的输入已经改变
        tasks.push(new ExploreInput(parent, inputOrdinal)); // 重新调度探索输入任务
        return; // 返回
      }
      input.setExplored(); // 标记输入为已探索
      for (RelSubset subset : input.getSet().subsets) { // 遍历输入集合的所有子集
        // Clear the LB cache as exploring state has changed.
        // 清除下界缓存，因为探索状态已改变
        input.getCluster().getMetadataQuery().clearCache(subset); // 清除元数据缓存
      }
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", parent).item("i", inputOrdinal); // 添加父节点和输入序号信息
    }
  }

  /**
   * Explores an input for a RelNode.
   * ExploreInput类：探索RelNode输入的任务
   */
  private class ExploreInput implements Task { // ExploreInput类：输入探索任务
    private final RelSubset group; // 要探索的RelSubset组
    private final RelNode parent; // 父RelNode
    private final int inputOrdinal; // 输入序号

    ExploreInput(RelNode parent, int inputOrdinal) { // 构造方法：创建探索输入任务
      this.group = (RelSubset) parent.getInput(inputOrdinal); // 获取输入RelSubset
      this.parent = parent; // 保存父RelNode
      this.inputOrdinal = inputOrdinal; // 保存输入序号
    }

    @Override public void perform() { // perform方法：执行探索任务
      if (!group.explore()) { // 如果组无法探索
        return; // 直接返回
      }
      tasks.push(new EnsureGroupExplored(group, parent, inputOrdinal)); // 推入确保组探索任务
      for (RelNode rel : group.set.rels) { // 遍历组中的所有RelNode
        if (planner.isLogical(rel)) { // 如果是逻辑节点
          tasks.push(new OptimizeMExpr(rel, group, true)); // 创建探索模式下的优化任务
        }
      }
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("group", group); // 添加组信息
    }
  }

  /**
   * Extracts rule matches from rule queue and adds them to task stack.
   * ApplyRules类：从规则队列中提取规则匹配并添加到任务栈
   */
  private class ApplyRules implements Task { // ApplyRules类：应用规则任务
    private final RelNode mExpr; // 要应用规则的RelNode
    private final RelSubset group; // 所属的RelSubset组
    private final boolean exploring; // 是否处于探索模式

    ApplyRules(RelNode mExpr, RelSubset group, boolean exploring) { // 构造方法：创建应用规则任务
      this.mExpr = mExpr; // 保存RelNode
      this.group = group; // 保存RelSubset
      this.exploring = exploring; // 保存探索模式标志
    }

    @Override public void perform() { // perform方法：执行应用规则任务
      Pair<RelNode, Predicate<VolcanoRuleMatch>> category = // 创建规则匹配分类
          exploring ? Pair.of(mExpr, planner::isTransformationRule) // 探索模式：只应用转换规则
              : Pair.of(mExpr, m -> true); // 非探索模式：应用所有规则
      VolcanoRuleMatch match = ruleQueue.popMatch(category); // 从规则队列中弹出匹配的规则
      while (match != null) { // 循环处理所有匹配的规则
        tasks.push(new ApplyRule(match, group, exploring)); // 推入应用规则任务
        match = ruleQueue.popMatch(category); // 继续弹出下一个匹配
      }
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", mExpr).item("exploring", exploring); // 添加mExpr和探索模式信息
    }
  }

  /**
   * Applies a rule match.
   * ApplyRule类：应用单个规则匹配的任务
   */
  private class ApplyRule implements GeneratorTask { // ApplyRule类：应用规则任务，实现GeneratorTask接口
    private final VolcanoRuleMatch match; // 规则匹配对象
    private final RelSubset group; // 所属的RelSubset组
    private final boolean exploring; // 是否处于探索模式

    ApplyRule(VolcanoRuleMatch match, RelSubset group, boolean exploring) { // 构造方法：创建应用规则任务
      this.match = match; // 保存规则匹配
      this.group = group; // 保存RelSubset
      this.exploring = exploring; // 保存探索模式标志
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("match", match).item("exploring", exploring); // 添加匹配和探索模式信息
    }

    @Override public void perform() { // perform方法：执行应用规则任务
      applyGenerator(this, match::onMatch); // 应用生成器任务，调用规则的onMatch方法
    }

    @Override public RelSubset group() { // group方法：返回所属组
      return group; // 返回RelSubset
    }

    @Override public boolean exploring() { // exploring方法：返回是否探索模式
      return exploring; // 返回探索模式标志
    }
  }

  /** Decides how to optimize a physical node. */
  private @Nullable Task getOptimizeInputTask(RelNode rel, RelSubset group) { // getOptimizeInputTask方法：决定如何优化物理节点
    // If the physical does not in current optimizing RelSubset, it firstly tries to
    // convert the physical node either by converter rule or traits pass though.
    // 如果物理节点不在当前优化的RelSubset中，首先尝试通过转换规则或trait传递来转换物理节点
    if (!rel.getTraitSet().satisfies(group.getTraitSet())) { // 如果节点的trait不满足组的trait
      RelNode passThroughRel = convert(rel, group); // 尝试转换节点
      if (passThroughRel == null) { // 如果转换失败
        LOGGER.debug("Skip optimizing because of traits: {}", rel); // 记录调试日志
        return null; // 返回null，跳过优化
      }
      final RelNode finalPassThroughRel = passThroughRel; // 保存转换后的节点
      applyGenerator(null, () -> // 应用生成器注册节点
          planner.register(finalPassThroughRel, group)); // 注册转换后的节点到组
      rel = passThroughRel; // 使用转换后的节点
    }
    boolean unProcess = false; // 未处理标志
    for (RelNode input : rel.getInputs()) { // 遍历所有输入
      RelOptCost winner = ((RelSubset) input).getWinnerCost(); // 获取输入的最优成本
      if (winner == null) { // 如果输入未优化
        unProcess = true; // 标记为未处理
        break; // 跳出循环
      }
    }
    // If the inputs are all processed, only DeriveTrait is required.
    // 如果所有输入都已处理，只需要推导trait
    if (!unProcess) { // 如果所有输入都已处理
      return new DeriveTrait(rel, group); // 返回推导trait任务
    }
    // If part of the inputs are not optimized, schedule for the node an OptimizeInput task,
    // which tried to optimize the inputs first and derive traits for further execution.
    // 如果部分输入未优化，为节点调度OptimizeInput任务
    // 该任务会先优化输入，然后推导trait以供进一步执行
    if (rel.getInputs().size() == 1) { // 如果只有一个输入
      return new OptimizeInput1(rel, group); // 返回单输入优化任务
    }
    return new OptimizeInputs(rel, group); // 返回多输入优化任务
  }

  /**
   * Tries to convert the physical node to another trait sets, either by converter rule
   * or traits pass through.
   * convert方法：尝试将物理节点转换为其他trait集合，通过转换规则或trait传递
   */
  private @Nullable RelNode convert(RelNode rel, RelSubset group) { // convert方法：转换物理节点
    if (!passThroughCache.contains(rel)) { // 如果节点不在传递缓存中
      if (checkLowerBound(rel, group)) { // 检查下界是否满足
        RelNode passThrough = group.passThrough(rel); // 尝试trait传递
        if (passThrough != null) { // 如果传递成功
          assert passThrough.getConvention() == rel.getConvention(); // 断言约定相同
          passThroughCache.add(passThrough); // 添加到缓存
          return passThrough; // 返回传递后的节点
        }
      } else { // 下界不满足
        LOGGER.debug("Skip pass though because of lower bound. LB = {}, UP = {}", // 记录调试日志
            rel, group.upperBound); // 输出下界和上界信息
      }
    }
    VolcanoRuleMatch match = // 查找转换规则匹配
        ruleQueue.popMatch(
            Pair.of(rel, // 节点
                m -> m.getRule() instanceof ConverterRule // 规则类型检查
                    && ((ConverterRule) m.getRule()).getOutTrait().satisfies( // 输出trait满足
                    requireNonNull(group.getTraitSet().getConvention(), // 获取约定
                        () -> "convention for " + group)))); // 错误消息
    if (match != null) { // 如果找到匹配
      tasks.add(new ApplyRule(match, group, false)); // 添加应用规则任务
    }
    return null; // 返回null表示转换失败
  }

  /**
   * Checks whether a node's lower bound is less than a RelSubset's upper bound.
   * checkLowerBound方法：检查节点的下界是否小于RelSubset的上界
   */
  private boolean checkLowerBound(RelNode rel, RelSubset group) { // checkLowerBound方法：检查下界
    RelOptCost upperBound = group.upperBound; // 获取组的上界
    if (upperBound.isInfinite()) { // 如果上界是无限的
      return true; // 返回true，允许优化
    }
    RelOptCost lb = planner.getLowerBound(rel); // 获取节点的下界
    return !upperBound.isLe(lb); // 返回上界是否不小于下界
  }

  /**
   * A task that optimizes input for physical nodes who has only one input.
   * This task can be replaced by OptimizeInputs but simplifies lots of logic.
   * OptimizeInput1类：优化只有一个输入的物理节点的任务
   * 这个任务可以被OptimizeInputs替代，但简化了很多逻辑
   */
  private class OptimizeInput1 implements Task { // OptimizeInput1类：单输入优化任务

    private final RelNode mExpr; // 要优化的RelNode
    private final RelSubset group; // 所属的RelSubset组

    OptimizeInput1(RelNode mExpr, RelSubset group) { // 构造方法：创建单输入优化任务
      this.mExpr = mExpr; // 保存RelNode
      this.group = group; // 保存RelSubset
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", mExpr).item("upperBound", group.upperBound); // 添加mExpr和上界信息
    }

    @Override public void perform() { // perform方法：执行优化任务
      RelOptCost upperBound = group.upperBound; // 获取组的上界
      RelOptCost upperForInput = planner.upperBoundForInputs(mExpr, upperBound); // 计算输入的上界
      if (upperForInput.isLe(planner.zeroCost)) { // 如果输入上界小于等于零成本
        LOGGER.debug( // 记录调试日志
            "Skip O_INPUT because of lower bound. UB4Inputs = {}, UB = {}", // 跳过优化输入
            upperForInput, upperBound); // 输出上界信息
        return; // 直接返回
      }

      RelSubset input = (RelSubset) mExpr.getInput(0); // 获取输入RelSubset

      // Apply enforcing rules.
      // 应用强制规则
      tasks.push(new DeriveTrait(mExpr, group)); // 推入推导trait任务

      tasks.push(new CheckInput(null, mExpr, input, 0, upperForInput)); // 推入检查输入任务
      tasks.push(new OptimizeGroup(input, upperForInput)); // 推入优化组任务
    }
  }

  /**
   * Optimizes a physical node's inputs.
   * This task calculates a proper upper bound for the input and invokes
   * the OptimizeGroup task. Group pruning mainly happens here when
   * the upper bound for an input is less than the input's lower bound
   * OptimizeInputs类：优化物理节点输入的任务
   * 这个任务为输入计算合适的上界并调用OptimizeGroup任务
   * 组剪枝主要发生在这里，当输入的上界小于输入的下界时
   */
  private class OptimizeInputs implements Task { // OptimizeInputs类：多输入优化任务

    private final RelNode mExpr; // 要优化的RelNode
    private final RelSubset group; // 所属的RelSubset组
    private final int childCount; // 子节点数量
    private RelOptCost upperBound; // 上界
    private RelOptCost upperForInput; // 输入的上界
    private int processingChild; // 当前处理的子节点索引
    private @Nullable List<RelOptCost> lowerBounds; // 各输入的下界列表
    private @Nullable RelOptCost lowerBoundSum; // 下界总和

    OptimizeInputs(RelNode rel, RelSubset group) { // 构造方法：创建多输入优化任务
      this.mExpr = rel; // 保存RelNode
      this.group = group; // 保存RelSubset
      this.upperBound = group.upperBound; // 初始化上界
      this.upperForInput = planner.infCost; // 初始化输入上界为无限
      this.childCount = rel.getInputs().size(); // 获取子节点数量
      this.processingChild = 0; // 初始化处理索引为0
    }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", mExpr).item("upperBound", upperBound) // 添加mExpr和上界信息
          .item("processingChild", processingChild); // 添加处理索引信息
    }

    @Override public void perform() { // perform方法：执行优化任务
      RelOptCost bestCost = group.bestCost; // 获取最佳成本
      if (!bestCost.isInfinite()) { // 如果最佳成本不是无限的
        // Calculate the upper bound for inputs.
        // 计算输入的上界
        if (bestCost.isLt(upperBound)) { // 如果最佳成本小于上界
          upperBound = bestCost; // 更新上界
          upperForInput = planner.upperBoundForInputs(mExpr, upperBound); // 计算输入上界
        }

        if (lowerBoundSum == null) { // 如果下界总和未计算
          if (upperForInput.isInfinite()) { // 如果输入上界是无限的
            upperForInput = planner.upperBoundForInputs(mExpr, upperBound); // 重新计算输入上界
          }
          List<RelOptCost> lowerBounds = this.lowerBounds = new ArrayList<>(childCount); // 创建下界列表
          for (RelNode input : mExpr.getInputs()) { // 遍历所有输入
            RelOptCost lb = planner.getLowerBound(input); // 获取输入的下界
            lowerBounds.add(lb); // 添加到列表
            lowerBoundSum = lowerBoundSum == null ? lb : lowerBoundSum.plus(lb); // 累加下界
          }
        }
        if (upperForInput.isLt(requireNonNull(lowerBoundSum, "lowerBoundSum"))) { // 如果输入上界小于下界总和
          LOGGER.debug( // 记录调试日志
              "Skip O_INPUT because of lower bound. LB = {}, UP = {}", // 跳过优化输入
              lowerBoundSum, upperForInput); // 输出下界和上界信息
          // Group is pruned.
          // 组被剪枝
          return; // 直接返回
        }
      }

      if (lowerBoundSum != null && lowerBoundSum.isInfinite()) { // 如果下界总和是无限的
        LOGGER.debug("Skip O_INPUT as one of the inputs fail to optimize"); // 记录调试日志
        return; // 直接返回
      }

      if (processingChild == 0) { // 如果是第一个子节点
        // Derive traits after all inputs are optimized successfully.
        // 在所有输入成功优化后推导trait
        tasks.push(new DeriveTrait(mExpr, group)); // 推入推导trait任务
      }

      while (processingChild < childCount) { // 循环处理所有子节点
        RelSubset input = // 获取当前子节点
            (RelSubset) mExpr.getInput(processingChild);

        RelOptCost winner = input.getWinnerCost(); // 获取子节点的最优成本
        if (winner != null) { // 如果子节点已优化
          ++ processingChild; // 移动到下一个子节点
          continue; // 继续循环
        }

        RelOptCost upper = upperForInput; // 获取上界
        if (!upper.isInfinite()) { // 如果上界不是无限的
          // UB(one input)
          //  = UB(current subset) - Parent's NonCumulativeCost - LB(other inputs)
          //  = UB(current subset) - Parent's NonCumulativeCost - LB(all inputs) + LB(current input)
          // 单个输入的上界计算公式
          //  = 当前子集上界 - 父节点非累积成本 - 其他输入下界
          //  = 当前子集上界 - 父节点非累积成本 - 所有输入下界 + 当前输入下界
          upper = upperForInput.minus(requireNonNull(lowerBoundSum, "lowerBoundSum")) // 减去下界总和
              .plus(requireNonNull(lowerBounds, "lowerBounds").get(processingChild)); // 加上当前输入下界
        }
        if (input.taskState != null && upper.isLe(input.upperBound)) { // 如果子节点已处理且上界小于等于子节点上界
          LOGGER.debug("Failed to optimize because of upper bound. LB = {}, UP = {}", // 记录调试日志
              lowerBoundSum, upperForInput); // 输出下界和上界信息
          return; // 直接返回
        }

        if (processingChild != childCount - 1) { // 如果不是最后一个子节点
          tasks.push(this); // 重新推入当前任务以继续处理
        }
        tasks.push(new CheckInput(this, mExpr, input, processingChild, upper)); // 推入检查输入任务
        tasks.push(new OptimizeGroup(input, upper)); // 推入优化组任务
        ++ processingChild; // 移动到下一个子节点
        break; // 跳出循环，等待子节点优化完成
      }
    }
  }

  /**
   * Ensures input is optimized correctly and modify context.
   * CheckInput类：确保输入正确优化并修改上下文的任务
   */
  private class CheckInput implements Task { // CheckInput类：检查输入任务

    private final @Nullable OptimizeInputs context; // 上下文（多输入优化任务）
    private final RelOptCost upper; // 上界
    private final RelNode parent; // 父RelNode
    private RelSubset input; // 输入RelSubset
    private final int i; // 输入序号

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("parent", parent).item("i", i); // 添加父节点和输入序号信息
    }

    CheckInput(@Nullable OptimizeInputs context, // 构造方法：创建检查输入任务
        RelNode parent, RelSubset input, int i, RelOptCost upper) {
      this.context = context; // 保存上下文
      this.parent = parent; // 保存父节点
      this.input = input; // 保存输入
      this.i = i; // 保存输入序号
      this.upper = upper; // 保存上界
    }

    @Override public void perform() { // perform方法：执行检查任务
      if (input != parent.getInput(i)) { // 如果输入已改变
        // The input has changed. So reschedule the optimize task.
        // 输入已改变，重新调度优化任务
        input = (RelSubset) parent.getInput(i); // 获取新的输入
        tasks.push(this); // 重新推入检查任务
        tasks.push(new OptimizeGroup(input, upper)); // 推入优化组任务
        return; // 返回
      }

      // Optimizing input completed. Update the context for other inputs.
      // 输入优化完成，更新其他输入的上下文
      if (context == null) { // 如果没有上下文（单输入情况）
        // If there is no other input, just return (no need to optimize other inputs).
        // 如果没有其他输入，直接返回（无需优化其他输入）
        return; // 返回
      }

      RelOptCost winner = input.getWinnerCost(); // 获取输入的最优成本
      if (winner == null) { // 如果输入优化失败
        // The input fails to optimize due to group pruning.
        // Then there's no need to optimize other inputs.
        // 输入因组剪枝而优化失败
        // 无需优化其他输入
        context.lowerBoundSum = planner.infCost; // 设置下界总和为无限
        return; // 返回
      }

      // Update the context.
      // 更新上下文
      RelOptCost lowerBoundSum = context.lowerBoundSum; // 获取下界总和
      if (lowerBoundSum != null && lowerBoundSum != planner.infCost) { // 如果下界总和有效
        List<RelOptCost> lowerBounds = requireNonNull(context.lowerBounds, "context.lowerBounds"); // 获取下界列表
        lowerBoundSum = lowerBoundSum.minus(lowerBounds.get(i)); // 减去当前输入的下界
        lowerBoundSum = lowerBoundSum.plus(winner); // 加上最优成本
        context.lowerBoundSum = lowerBoundSum; // 更新下界总和
        lowerBounds.set(i, winner); // 更新下界列表
      }
    }
  }

  /**
   * Derives traits for already optimized physical nodes.
   * DeriveTrait类：为已优化的物理节点推导trait的任务
   */
  private class DeriveTrait implements GeneratorTask { // DeriveTrait类：推导trait任务

    private final RelNode mExpr; // 要推导trait的RelNode
    private final RelSubset group; // 所属的RelSubset组

    DeriveTrait(RelNode mExpr, RelSubset group) { // 构造方法：创建推导trait任务
      this.mExpr = mExpr; // 保存RelNode
      this.group = group; // 保存RelSubset
    }

    @Override public void perform() { // perform方法：执行推导任务
      List<RelNode> inputs = mExpr.getInputs(); // 获取所有输入
      for (RelNode input : inputs) { // 遍历输入
        if (((RelSubset) input).getWinnerCost() == null) { // 如果输入未优化
          // Fail to optimize input, then no need to deliver traits.
          // 输入优化失败，无需推导trait
          return; // 直接返回
        }
      }

      // In case some implementations use rules to convert between different physical conventions.
      // Note that this is deprecated and will be removed in the future.
      // 以防某些实现使用规则在不同物理约定之间转换
      // 注意：这是已弃用的功能，未来将移除
      tasks.push(new ApplyRules(mExpr, group, false)); // 推入应用规则任务

      // Derive traits from inputs.
      // 从输入推导trait
      if (!passThroughCache.contains(mExpr)) { // 如果节点不在传递缓存中
        applyGenerator(this, this::derive); // 应用生成器执行推导
      }
    }

    private void derive() { // derive方法：执行trait推导
      if (!(mExpr instanceof PhysicalNode) // 如果不是物理节点
          || ((PhysicalNode) mExpr).getDeriveMode() == DeriveMode.PROHIBITED) { // 或推导模式为禁止
        return; // 直接返回
      }

      PhysicalNode rel = (PhysicalNode) mExpr; // 转换为物理节点
      DeriveMode mode = rel.getDeriveMode(); // 获取推导模式
      int arity = rel.getInputs().size(); // 获取输入数量
      // For OMAKASE.
      // 为OMAKASE模式准备输入trait列表
      List<List<RelTraitSet>> inputTraits = new ArrayList<>(arity); // 创建输入trait列表

      for (int i = 0; i < arity; i++) { // 遍历所有输入
        int childId = i; // 子节点ID
        if (mode == DeriveMode.RIGHT_FIRST) { // 如果是右优先模式
          childId = arity - i - 1; // 反向计算子节点ID
        }

        RelSubset input = (RelSubset) rel.getInput(childId); // 获取输入RelSubset
        List<RelTraitSet> traits = new ArrayList<>(); // 创建trait列表
        inputTraits.add(traits); // 添加到输入trait列表

        final int numSubset = input.set.subsets.size(); // 获取子集数量
        for (int j = 0; j < numSubset; j++) { // 遍历所有子集
          RelSubset subset = input.set.subsets.get(j); // 获取子集
          if (!subset.isDelivered() || subset.getTraitSet() // 如果子集未交付或traitSet等于默认traitSet
              .equalsSansConvention(rel.getCluster().traitSet())) {
            // Ideally we should stop deriving new relnodes when the
            // subset's traitSet equals with input traitSet, but
            // in case someone manually builds a physical relnode
            // tree, which is highly discouraged, without specifying
            // correct traitSet, e.g.
            //   EnumerableFilter  [].ANY
            //       -> EnumerableMergeJoin  [a].Hash[a]
            // We should still be able to derive the correct traitSet
            // for the dumb filter, even though the filter's traitSet
            // should be derived from the MergeJoin when it is created.
            // But if the subset's traitSet equals with the default
            // empty traitSet sans convention (the default traitSet
            // from cluster may have logical convention, NONE, which
            // is not interesting), we are safe to ignore it, because
            // a physical filter with non default traitSet, but has a
            // input with default empty traitSet, e.g.
            //   EnumerableFilter  [a].Hash[a]
            //       -> EnumerableProject  [].ANY
            // is definitely wrong, we should fail fast.
            // 理想情况下，当子集的traitSet等于输入traitSet时，我们应该停止推导新的relnode
            // 但如果有人手动构建物理relnode树（这是强烈不鼓励的），没有指定正确的traitSet，例如：
            //   EnumerableFilter  [].ANY
            //       -> EnumerableMergeJoin  [a].Hash[a]
            // 我们仍然应该能够为这个愚蠢的过滤器推导正确的traitSet
            // 尽管过滤器的traitSet应该在创建时从MergeJoin推导
            // 但如果子集的traitSet等于默认的空traitSet（不包括约定）
            // （来自cluster的默认traitSet可能有逻辑约定NONE，这不重要）
            // 我们可以安全地忽略它，因为
            // 一个具有非默认traitSet的物理过滤器，但有一个具有默认空traitSet的输入，例如：
            //   EnumerableFilter  [a].Hash[a]
            //       -> EnumerableProject  [].ANY
            // 肯定是错误的，我们应该快速失败
            continue; // 跳过
          }

          if (mode == DeriveMode.OMAKASE) { // 如果是OMAKASE模式

                      traits.add(subset.getTraitSet()); // 添加trait到列表

                    } else { // 其他模式

                      RelNode newRel = rel.derive(subset.getTraitSet(), childId); // 推导新的RelNode

                      if (newRel != null && !planner.isRegistered(newRel)) { // 如果推导成功且未注册

                        RelNode newInput = newRel.getInput(childId); // 获取新节点的输入

                        assert newInput instanceof RelSubset; // 断言输入是RelSubset

                        if (newInput == subset) { // 如果新输入等于子集

          

                          // If the child subset is used to derive new traits for

                          // current relnode, the subset will be marked REQUIRED

                          // when registering the new derived relnode and later

                          // will add enforcers between other delivered subsets.

                          // e.g. a MergeJoin request both inputs hash distributed

                          // by [a,b] sorted by [a,b]. If the left input R1 happens to

                          // be distributed by [a], the MergeJoin can derive new

                          // traits from this input and request both input to be

                          // distributed by [a] sorted by [a,b]. In case there is a

                          // alternative R2 with ANY distribution in the left input's

                          // RelSet, we may end up with requesting hash distribution

                          // [a] on alternative R2, which is unnecessary and waste,

                          // because we request distribution by [a] because of R1 can

                          // deliver the exact same distribution and we don't need to

                          // enforce properties on other subsets that can't satisfy

                          // the specific trait requirement.

                          // Here we add a constraint that {@code newInput == subset},

                          // because if the delivered child subset is HASH[a], but

                          // we require HASH[a].SORT[a,b], we still need to enable

                          // property enforcement on the required subset. Otherwise,

                          // we need to restrict enforcement between HASH[a].SORT[a,b]

                          // and HASH[a] only, which will make things a little bit

                          // complicated. We might optimize it in the future.

                          // 如果子集用于为当前relnode推导新trait，子集将在注册新的推导relnode时被标记为REQUIRED

                          // 稍后将在其他交付的子集之间添加强制器

                          // 例如：MergeJoin要求两个输入都按[a,b]哈希分布并按[a,b]排序

                          // 如果左输入R1恰好按[a]分布，MergeJoin可以从这个输入推导新trait

                          // 并要求两个输入都按[a]分布并按[a,b]排序

                          // 如果左输入的RelSet中有一个替代R2具有ANY分布

                          // 我们最终可能会在替代R2上请求哈希分布[a]，这是不必要的浪费

                          // 因为我们请求[a]分布是因为R1可以交付完全相同的分布

                          // 我们不需要在无法满足特定trait要求的其他子集上强制属性

                          // 这里我们添加了一个约束{@code newInput == subset}

                          // 因为如果交付的子子集是HASH[a]，但我们要求HASH[a].SORT[a,b]

                          // 我们仍然需要在要求的子集上启用属性强制

                          // 否则，我们需要限制强制只在HASH[a].SORT[a,b]和HASH[a]之间

                          // 这会使事情变得有点复杂。我们将来可能会优化它

                          subset.disableEnforcing(); // 禁用强制

                        }

                        RelSubset relSubset = planner.register(newRel, rel); // 注册新的RelNode

                        assert relSubset.set == planner.getSubsetNonNull(rel).set; // 断言集合相同

                      }

                    }

                  }

          

                  if (mode == DeriveMode.LEFT_FIRST // 如果是左优先模式

                      || mode == DeriveMode.RIGHT_FIRST) { // 或右优先模式

                    break; // 跳出循环

                  }

                }

          

                if (mode == DeriveMode.OMAKASE) { // 如果是OMAKASE模式

                  List<RelNode> relList = rel.derive(inputTraits); // 批量推导RelNode

                  for (RelNode relNode : relList) { // 遍历推导结果

                    if (!planner.isRegistered(relNode)) { // 如果未注册

                      planner.register(relNode, rel); // 注册RelNode

                    }

                  }

                }

              }

    @Override public void describe(TaskDescriptor desc) { // describe方法：描述任务信息
      desc.item("mExpr", mExpr).item("group", group); // 添加mExpr和组信息
    }

    @Override public RelSubset group() { // group方法：返回所属组
      return group; // 返回RelSubset
    }

    @Override public boolean exploring() { // exploring方法：返回是否探索模式
      return false; // 总是返回false（不是探索模式）
    }

    @Override public boolean onProduce(RelNode node) { // onProduce方法：当产生新RelNode时的回调
      passThroughCache.add(node); // 添加到传递缓存
      return true; // 返回true表示继续处理
    }
  }
}
