/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.plan.volcano; // 包声明：Volcano优化器相关的规则调用类所在包

import org.apache.calcite.plan.RelHintsPropagator; // 导入：Rel提示传播器，用于传播关系提示信息
import org.apache.calcite.plan.RelOptListener; // 导入：优化器监听器接口，用于监听优化过程中的事件
import org.apache.calcite.plan.RelOptRuleCall; // 导入：优化规则调用基类，VolcanoRuleCall继承自此类
import org.apache.calcite.plan.RelOptRuleOperand; // 导入：优化规则操作数，定义规则匹配的模式
import org.apache.calcite.plan.RelOptRuleOperandChildPolicy; // 导入：操作数子节点匹配策略枚举
import org.apache.calcite.rel.PhysicalNode; // 导入：物理节点接口，表示物理执行计划节点
import org.apache.calcite.rel.RelNode; // 导入：关系表达式基类，表示关系代数操作
import org.apache.calcite.rel.rules.SubstitutionRule; // 导入：替换规则接口，用于等价替换
import org.apache.calcite.rel.rules.TransformationRule; // 导入：转换规则接口，用于逻辑转换

import com.google.common.collect.ImmutableList; // 导入：Google Guava不可变列表类
import com.google.common.collect.ImmutableMap; // 导入：Google Guava不可变映射类
import com.google.common.collect.Lists; // 导入：Google Guava列表工具类

import org.checkerframework.checker.nullness.qual.Nullable; // 导入：可空性注解，标记可能为null的值

import java.util.ArrayList; // 导入：Java集合框架ArrayList类
import java.util.Arrays; // 导入：Java数组工具类
import java.util.Collection; // 导入：Java集合框架Collection接口
import java.util.HashSet; // 导入：Java集合框架HashSet类
import java.util.List; // 导入：Java集合框架List接口
import java.util.Map; // 导入：Java集合框架Map接口
import java.util.Set; // 导入：Java集合框架Set接口
import java.util.stream.Collectors; // 导入：Java流式处理Collectors工具类

import static org.apache.calcite.linq4j.Nullness.castNonNull; // 导入：静态方法，用于将可能为null的值转换为非null

import static java.util.Objects.requireNonNull; // 导入：静态方法，用于检查对象是否为null

/**
 * <code>VolcanoRuleCall</code> implements the {@link RelOptRuleCall} interface
 * for VolcanoPlanner. // VolcanoRuleCall类实现了RelOptRuleCall接口，专门用于VolcanoPlanner优化器
 * 
 * 类作用：该类是Volcano优化器中规则调用的核心实现，负责：
 * 1. 匹配优化规则的操作数（operands），即检查规则是否适用于当前的关系表达式
 * 2. 当规则匹配成功时，执行规则转换操作，生成新的关系表达式
 * 3. 管理规则调用的生命周期，包括匹配、执行和结果注册
 * 4. 提供递归匹配机制，支持复杂的规则模式匹配（如父子节点匹配）
 * 5. 与VolcanoPlanner紧密协作，确保转换后的表达式正确注册到优化器中
 * 
 * 核心概念：
 * - 操作数（Operand）：规则定义的匹配模式，包含类型、父子关系等约束
 * - 匹配（Match）：检查给定的关系表达式是否符合操作数定义的模式
 * - 转换（Transform）：规则匹配成功后，将输入表达式转换为新的表达式
 * - 等价集（Equivalence）：优化器维护的等价关系集合，用于记录等价的执行计划
 */
public class VolcanoRuleCall extends RelOptRuleCall { // 类定义：继承自RelOptRuleCall基类
  //~ Instance fields -------------------------------------------------------- // 成员变量区域标记

  protected final VolcanoPlanner volcanoPlanner; // 成员变量：Volcano优化器引用，用于访问优化器的核心功能（如注册表达式、获取子集等），final修饰表示初始化后不可改变

  /**
   * List of {@link RelNode} generated by this call. For debugging purposes.
   * // 成员变量注释：该列表存储本次规则调用生成的所有关系表达式，主要用于调试目的，可以在日志中查看规则转换的效果
   */
  private @Nullable List<RelNode> generatedRelList; // 成员变量：生成的RelNode列表，@Nullable表示可能为null，仅用于调试时记录生成的节点

  //~ Constructors ----------------------------------------------------------- // 构造方法区域标记

  /**
   * Creates a rule call, internal, with array to hold bindings.
   * // 构造方法注释：创建一个规则调用对象，内部使用，需要提供用于存储绑定关系表达式的数组
   *
   * @param planner Planner // Volcano优化器实例
   * @param operand First operand of the rule // 规则的第一个操作数
   * @param rels    Array which will hold the matched relational expressions // 用于存储匹配的关系表达式的数组
   * @param nodeInputs For each node which matched with {@code matchAnyChildren} // 对于使用matchAnyChildren匹配的节点，存储其子节点列表的映射
   *                   = true, a list of the node's inputs
   */
  protected VolcanoRuleCall( // 构造方法：创建规则调用对象，protected修饰表示只能在包内或子类中使用
      VolcanoPlanner planner, // 参数：Volcano优化器
      RelOptRuleOperand operand, // 参数：规则的操作数
      RelNode[] rels, // 参数：关系表达式数组，存储匹配的节点
      Map<RelNode, List<RelNode>> nodeInputs) { // 参数：节点输入映射，记录节点及其子节点
    super(planner, operand, rels, nodeInputs); // 调用父类RelOptRuleCall的构造方法，初始化父类字段
    this.volcanoPlanner = planner; // 初始化成员变量volcanoPlanner
  } // 构造方法结束

  /**
   * Creates a rule call. // 构造方法注释：创建一个规则调用对象，简化版本
   *
   * @param planner Planner // Volcano优化器实例
   * @param operand First operand of the rule // 规则的第一个操作数
   */
  VolcanoRuleCall( // 构造方法：创建规则调用对象，包级别访问权限
      VolcanoPlanner planner, // 参数：Volcano优化器
      RelOptRuleOperand operand) { // 参数：规则的操作数
    this( // 调用本类的另一个构造方法
        planner, // 传递优化器
        operand, // 传递操作数
        new RelNode[operand.getRule().operands.size()], // 创建关系表达式数组，大小为规则操作数的数量
        ImmutableMap.of()); // 创建空的不可变映射，用于nodeInputs
  } // 构造方法结束

  //~ Methods ---------------------------------------------------------------- // 方法区域标记

  @Override public void transformTo(RelNode rel, Map<RelNode, RelNode> equiv, // 方法：将当前匹配的关系表达式转换为新的关系表达式，@Override表示重写父类方法
      RelHintsPropagator handler) { // 参数：新的关系表达式，等价关系映射，提示传播器
    if (rel instanceof PhysicalNode // 检查：如果新的关系表达式是物理节点
        && rule instanceof TransformationRule) { // 且当前规则是转换规则（不是物理规则）
      throw new RuntimeException( // 抛出运行时异常：转换规则不能生成物理节点
          rel + " is a PhysicalNode, which is not allowed in " + rule); // 异常信息
    } // 条件检查结束

    rel = handler.propagate(rels[0], rel); // 使用提示传播器将原表达式的提示传播到新表达式
    if (LOGGER.isDebugEnabled()) { // 如果调试日志启用
      LOGGER.debug("Transform to: rel#{} via {}{}", rel.getId(), getRule(), // 记录转换信息：目标节点ID、规则名称、等价关系
          equiv.isEmpty() ? "" : " with equivalences " + equiv); // 如果有等价关系则记录
      if (generatedRelList != null) { // 如果生成的节点列表不为null
        generatedRelList.add(rel); // 将新节点添加到列表中，用于调试
      } // 内层if结束
    } // 外层if结束
    try { // 开始try块，处理可能出现的异常
      // It's possible that rel is a subset or is already registered. // 注释：新节点可能是子集或已经注册
      // Is there still a point in continuing? Yes, because we might // 注释：是否需要继续？是的，因为我们可能
      // discover that two sets of expressions are actually equivalent. // 注释：发现两组表达式实际上是等价的
      if (volcanoPlanner.getListener() != null) { // 如果优化器有监听器
        RelOptListener.RuleProductionEvent event = // 创建规则生产事件，表示规则开始生成节点
            new RelOptListener.RuleProductionEvent( // 事件构造
                volcanoPlanner, // 优化器
                rel, // 生成的节点
                this, // 当前规则调用
                true); // 事件开始标志
        volcanoPlanner.getListener().ruleProductionSucceeded(event); // 通知监听器规则生产开始
      } // if结束

      if (this.getRule() instanceof SubstitutionRule // 如果当前规则是替换规则
          && ((SubstitutionRule) getRule()).autoPruneOld()) { // 且规则配置为自动修剪旧节点
        volcanoPlanner.prune(rels[0]); // 修剪原始节点（降低其重要性，减少后续匹配）
      } // if结束

      // Registering the root relational expression implicitly registers // 注释：注册根关系表达式会隐式注册
      // its descendants. Register any explicit equivalences first, so we // 注释：其子节点。先注册显式的等价关系，以避免
      // don't register twice and cause churn. // 注释：重复注册和性能开销
      for (Map.Entry<RelNode, RelNode> entry : equiv.entrySet()) { // 遍历等价关系映射
        volcanoPlanner.ensureRegistered( // 确保节点已注册
            entry.getKey(), entry.getValue()); // 注册键节点，以值节点为等价参考
      } // for循环结束
      // The subset is not used, but we need it, just for debugging // 注释：子集变量未使用，但需要它用于调试
      @SuppressWarnings("unused") // 抑制未使用变量警告
      RelSubset subset = volcanoPlanner.ensureRegistered(rel, rels[0]); // 注册新节点，以原节点为等价参考，获取返回的子集

      if (volcanoPlanner.getListener() != null) { // 如果优化器有监听器
        RelOptListener.RuleProductionEvent event = // 创建规则生产事件，表示规则生成完成
            new RelOptListener.RuleProductionEvent( // 事件构造
                volcanoPlanner, // 优化器
                rel, // 生成的节点
                this, // 当前规则调用
                false); // 事件结束标志
        volcanoPlanner.getListener().ruleProductionSucceeded(event); // 通知监听器规则生产结束
      } // if结束
    } catch (Exception e) { // 捕获异常
      throw new RuntimeException("Error occurred while applying rule " // 抛出运行时异常：应用规则时出错
          + getRule(), e); // 异常信息包含规则名称和原始异常
    } // try-catch结束
  } // transformTo方法结束

  /**
   * Called when all operands have matched. // 方法注释：当所有操作数都匹配成功时调用此方法
   * 
   * 方法作用：这是规则匹配成功后的核心执行方法，负责：
   * 1. 检查规则是否被排除（通过过滤器或提示）
   * 2. 验证所有匹配的操作数是否仍然有效（未被修剪、未被删除）
   * 3. 通知监听器规则尝试执行
   * 4. 调用规则的onMatch方法执行实际转换
   * 5. 记录生成的节点数量，用于调试
   * 6. 通知监听器规则执行完成
   * 
   * 执行流程：
   * - 预检查：规则排除、操作数有效性验证
   * - 执行前通知：发送RuleAttemptedEvent（开始）
   * - 规则执行：调用rule.onMatch(this)
   * - 执行后处理：记录生成节点、发送RuleAttemptedEvent（结束）
   */
  protected void onMatch() { // 方法：所有操作数匹配成功后的处理逻辑
    assert getRule().matches(this); // 断言：规则必须匹配当前调用
    volcanoPlanner.checkCancel(); // 检查优化器是否被取消
    try { // 开始try块，处理可能出现的异常
      if (volcanoPlanner.isRuleExcluded(getRule())) { // 检查：规则是否被排除过滤器排除
        LOGGER.debug("Rule [{}] not fired due to exclusion filter", getRule()); // 记录调试日志：规则因排除过滤器未触发
        return; // 直接返回，不执行规则
      } // if结束

      if (isRuleExcluded()) { // 检查：规则是否被提示排除
        LOGGER.debug("Rule [{}] not fired due to exclusion hint", getRule()); // 记录调试日志：规则因排除提示未触发
        return; // 直接返回，不执行规则
      } // if结束

      for (int i = 0; i < rels.length; i++) { // 遍历所有匹配的关系表达式
        RelNode rel = rels[i]; // 获取当前关系表达式
        RelSubset subset = volcanoPlanner.getSubset(rel); // 获取该节点所属的子集

        if (subset == null) { // 如果子集为null（节点未注册）
          LOGGER.debug( // 记录调试日志
              "Rule [{}] not fired because operand #{} ({}) has no subset", // 规则未触发，因为操作数没有子集
              getRule(), i, rel); // 日志参数
          return; // 直接返回，不执行规则
        } // if结束

        if ((subset.set.equivalentSet != null) // 如果子集的等价集不为null（表示子集已合并到其他等价集）
            // When rename RelNode via VolcanoPlanner#rename(RelNode rel), // 注释：当通过VolcanoPlanner重命名节点时
            // we may remove rel from its subset: "subset.set.rels.remove(rel)". // 注释：可能会从子集中移除节点
            // Skip rule match when the rel has been removed from set. // 注释：当节点从集合中移除时跳过规则匹配
            || (subset != rel && !subset.contains(rel))) { // 或者子集不等于节点且子集不包含该节点
          LOGGER.debug( // 记录调试日志
              "Rule [{}] not fired because operand #{} ({}) belongs to obsolete set", // 规则未触发，因为操作数属于过时的集合
              getRule(), i, rel); // 日志参数
          return; // 直接返回，不执行规则
        } // if结束

        if (volcanoPlanner.prunedNodes.contains(rel)) { // 如果节点已被修剪（重要性为0）
          LOGGER.debug("Rule [{}] not fired because operand #{} ({}) has importance=0", // 记录调试日志：规则未触发，因为操作数重要性为0
              getRule(), i, rel); // 日志参数
          return; // 直接返回，不执行规则
        } // if结束
      } // for循环结束

      if (volcanoPlanner.getListener() != null) { // 如果优化器有监听器
        RelOptListener.RuleAttemptedEvent event = // 创建规则尝试事件，表示规则开始执行
            new RelOptListener.RuleAttemptedEvent( // 事件构造
                volcanoPlanner, // 优化器
                rels[0], // 第一个匹配的节点
                this, // 当前规则调用
                true); // 事件开始标志
        volcanoPlanner.getListener().ruleAttempted(event); // 通知监听器规则尝试开始
      } // if结束

      if (LOGGER.isDebugEnabled()) { // 如果调试日志启用
        this.generatedRelList = new ArrayList<>(); // 初始化生成节点列表，用于记录本次规则调用生成的节点
      } // if结束

      volcanoPlanner.ruleCallStack.push(this); // 将当前规则调用压入调用栈，用于检测循环调用
      try { // 开始try块，确保规则执行后能清理调用栈
        getRule().onMatch(this); // 调用规则的onMatch方法，执行实际的转换逻辑
      } finally { // finally块确保总是执行
        volcanoPlanner.ruleCallStack.pop(); // 将当前规则调用从调用栈中弹出
      } // try-finally结束

      if (generatedRelList != null) { // 如果生成节点列表不为null
        if (generatedRelList.isEmpty()) { // 如果列表为空（没有生成节点）
          LOGGER.debug("call#{} generated 0 successors.", id); // 记录调试日志：本次调用生成了0个后继节点
        } else { // 如果列表不为空
          LOGGER.debug( // 记录调试日志
              "call#{} generated {} successors: {}", // 本次调用生成了N个后继节点
              id, generatedRelList.size(), generatedRelList); // 日志参数：调用ID、生成数量、节点列表
        } // 内层else结束
        this.generatedRelList = null; // 清空生成节点列表，释放内存
      } // 外层if结束

      if (volcanoPlanner.getListener() != null) { // 如果优化器有监听器
        RelOptListener.RuleAttemptedEvent event = // 创建规则尝试事件，表示规则执行完成
            new RelOptListener.RuleAttemptedEvent( // 事件构造
                volcanoPlanner, // 优化器
                rels[0], // 第一个匹配的节点
                this, // 当前规则调用
                false); // 事件结束标志
        volcanoPlanner.getListener().ruleAttempted(event); // 通知监听器规则尝试结束
      } // if结束
    } catch (Exception e) { // 捕获异常
      throw new RuntimeException("Error while applying rule " + getRule() // 抛出运行时异常：应用规则时出错
          + ", args " + Arrays.toString(rels), e); // 异常信息包含规则名称和参数
    } // try-catch结束
  } // onMatch方法结束

  /**
   * Applies this rule, with a given relational expression in the first slot. // 方法注释：应用规则，将给定的关系表达式放在第一个位置
   * 
   * 方法作用：这是规则匹配的入口方法，用于启动规则匹配过程：
   * 1. 验证给定的关系表达式是否匹配第一个操作数
   * 2. 将关系表达式绑定到操作数数组中
   * 3. 启动递归匹配过程，查找其他操作数的匹配
   * 
   * 参数说明：
   * - rel：要匹配的关系表达式，通常是优化器正在处理的节点
   * 
   * 调用时机：
   * - 当优化器发现一个可能匹配规则的关系表达式时调用此方法
   * - 这是规则匹配的起点，后续的匹配由matchRecurse递归完成
   */
  void match(RelNode rel) { // 方法：开始规则匹配，给定第一个关系表达式
    assert getOperand0().matches(rel) : "precondition"; // 断言：第一个操作数必须匹配给定的关系表达式
    final int solve = 0; // 初始化solve顺序为0，表示从第一个操作数开始
    int operandOrdinal = castNonNull(getOperand0().solveOrder)[solve]; // 获取第一个操作数在规则中的序号
    this.rels[operandOrdinal] = rel; // 将给定的关系表达式绑定到操作数数组的对应位置
    matchRecurse(solve + 1); // 递归匹配剩余的操作数，从solve+1开始
  } // match方法结束

  /**
   * Recursively matches operands above a given solve order. // 方法注释：递归匹配给定solve顺序之上的操作数
   *
   * @param solve Solve order of operand (&gt; 0 and &le; the operand count) // 参数：操作数的solve顺序（大于0且小于等于操作数数量）
   * 
   * 方法作用：这是规则匹配的核心递归方法，负责：
   * 1. 检查是否所有操作数都已匹配，如果是则调用onMatch执行规则
   * 2. 根据solve顺序确定下一个要匹配的操作数
   * 3. 判断匹配方向：向上（匹配父节点）或向下（匹配子节点）
   * 4. 查找符合条件的候选节点（successors）
   * 5. 递归尝试每个候选节点，直到找到完整匹配或所有候选都失败
   * 
   * 核心概念：
   * - Solve顺序：操作数的匹配顺序，决定了递归的方向和策略
   * - Ascending（向上）：从子节点匹配到父节点，查找父节点作为候选
   * - Descending（向下）：从父节点匹配到子节点，查找子节点作为候选
   * - UNORDERED策略：子节点可以匹配任意位置，需要特殊处理
   * 
   * 匹配流程：
   * 1. 如果所有操作数都已匹配（solve == operands.size()），检查规则是否匹配，如果匹配则执行规则
   * 2. 否则，根据solve顺序获取下一个操作数
   * 3. 判断匹配方向（ascending或descending）
   * 4. 根据方向和策略查找候选节点
   * 5. 对每个候选节点，验证是否满足约束条件
   * 6. 递归调用matchRecurse继续匹配下一个操作数
   */
  private void matchRecurse(int solve) { // 方法：递归匹配操作数
    assert solve > 0; // 断言：solve必须大于0
    assert solve <= rule.operands.size(); // 断言：solve不能超过操作数数量
    final List<RelOptRuleOperand> operands = getRule().operands; // 获取规则的所有操作数
    if (solve == operands.size()) { // 如果所有操作数都已匹配
      // We have matched all operands. Now ask the rule whether it // 注释：我们已经匹配了所有操作数。现在询问规则是否
      // matches; this gives the rule chance to apply side-conditions. // 注释：匹配；这给了规则应用附加条件的机会
      // If the side-conditions are satisfied, we have a match. // 注释：如果附加条件满足，我们就有一个匹配
      if (getRule().matches(this)) { // 调用规则的matches方法，检查附加条件
        onMatch(); // 如果所有条件都满足，执行规则转换
      } // if结束
    } else { // 还有操作数未匹配
      final int[] solveOrder = castNonNull(operand0.solveOrder); // 获取操作数的solve顺序数组
      final int operandOrdinal = solveOrder[solve]; // 获取当前要匹配的操作数在规则中的序号
      final int previousOperandOrdinal = solveOrder[solve - 1]; // 获取上一个操作数在规则中的序号
      boolean ascending = operandOrdinal < previousOperandOrdinal; // 判断匹配方向：true表示向上（匹配父节点），false表示向下（匹配子节点）
      final RelOptRuleOperand previousOperand = // 获取上一个操作数对象
          operands.get(previousOperandOrdinal); 
      final RelOptRuleOperand operand = // 获取当前操作数对象
          operands.get(operandOrdinal); 
      final RelNode previous = rels[previousOperandOrdinal]; // 获取上一个匹配的关系表达式

      final RelOptRuleOperand parentOperand; // 声明父操作数变量
      final Collection<? extends RelNode> successors; // 声明候选节点集合变量
      if (ascending) { // 如果是向上匹配（从子到父）
        assert previousOperand.getParent() == operand; // 断言：上一个操作数的父节点必须是当前操作数
        assert operand.getMatchedClass() != RelSubset.class; // 断言：向上匹配时，操作数不能匹配RelSubset类
        if (previousOperand.getMatchedClass() != RelSubset.class // 如果上一个操作数不匹配RelSubset类
            && previous instanceof RelSubset) { // 但上一个节点是RelSubset
          throw new RuntimeException("RelSubset should not match with " // 抛出异常：RelSubset不应该匹配该操作数
              + previousOperand.getMatchedClass().getSimpleName()); // 异常信息
        } // if结束
        parentOperand = operand; // 父操作数就是当前操作数
        final RelSubset subset = volcanoPlanner.getSubsetNonNull(previous); // 获取上一个节点所属的子集（非null）
        successors = subset.getParentRels(); // 获取该子集的所有父节点作为候选
      } else { // 如果是向下匹配（从父到子）
        parentOperand = // 获取当前操作数的父操作数
            requireNonNull(operand.getParent(), // 要求父操作数不能为null
                () -> "operand.getParent() for " + operand); // 如果为null，提供错误信息
        final RelNode parentRel = rels[parentOperand.ordinalInRule]; // 获取父操作数匹配的关系表达式
        final List<RelNode> inputs = parentRel.getInputs(); // 获取父节点的所有输入
        // if the child is unordered, then add all rels in all input subsets to the successors list // 注释：如果子节点是无序的，则将所有输入子集中的所有关系表达式添加到候选列表
        // because unordered can match child in any ordinal // 注释：因为无序可以匹配任意位置的子节点
        if (parentOperand.childPolicy == RelOptRuleOperandChildPolicy.UNORDERED) { // 如果子节点策略是无序的
          if (operand.getMatchedClass() == RelSubset.class) { // 如果操作数匹配RelSubset类
            // Find all the sibling subsets that satisfy this subset's traitSet // 注释：找到所有满足该子集traitSet的兄弟子集
            successors = inputs.stream() // 将输入列表转换为流
              .flatMap(subset -> ((RelSubset) subset).getSubsetsSatisfyingThis()) // 扁平化：获取每个子集满足条件的兄弟子集
              .collect(Collectors.toList()); // 收集为列表
          } else { // 如果操作数不匹配RelSubset类
            List<RelNode> allRelsInAllSubsets = new ArrayList<>(); // 创建列表，存储所有子集中的所有关系表达式
            Set<RelNode> duplicates = new HashSet<>(); // 创建集合，用于去重
            for (RelNode input : inputs) { // 遍历所有输入
              if (!duplicates.add(input)) { // 如果输入已经存在于重复集合中
                // Ignore duplicate subsets // 注释：忽略重复的子集
                continue; // 跳过
              } // if结束
              RelSubset inputSubset = (RelSubset) input; // 将输入转换为RelSubset
              for (RelNode rel : inputSubset.getRels()) { // 遍历子集中的所有关系表达式
                if (!duplicates.add(rel)) { // 如果关系表达式已经存在于重复集合中
                  // Ignore duplicate relations // 注释：忽略重复的关系表达式
                  continue; // 跳过
                } // if结束
                allRelsInAllSubsets.add(rel); // 将关系表达式添加到列表中
              } // 内层for结束
            } // 外层for结束
            successors = allRelsInAllSubsets; // 候选就是所有子集中的所有关系表达式
          } // else结束
        } else if (operand.ordinalInParent < inputs.size()) { // 如果子节点策略不是无序的，且操作数在父节点中的序号有效
          // child policy is not unordered // 注释：子节点策略不是无序的
          // we need to find the exact input node based on child operand's ordinalInParent // 注释：我们需要根据子操作数的ordinalInParent找到确切的输入节点
          final RelSubset subset = // 获取指定位置的输入子集
              (RelSubset) inputs.get(operand.ordinalInParent); 
          if (operand.getMatchedClass() == RelSubset.class) { // 如果操作数匹配RelSubset类
            // Find all the sibling subsets that satisfy this subset'straitSet // 注释：找到所有满足该子集traitSet的兄弟子集
            successors = // 获取满足条件的兄弟子集
              subset.getSubsetsSatisfyingThis().collect(Collectors.toList()); // 收集为列表
          } else { // 如果操作数不匹配RelSubset类
            successors = subset.getRelList(); // 候选就是子集中的所有关系表达式
          } // else结束
        } else { // 如果操作数在父节点中的序号无效
          // The operand expects parentRel to have a certain number // 注释：操作数期望父节点有特定数量的输入
          // of inputs and it does not. // 注释：但实际上没有
          successors = ImmutableList.of(); // 候选列表为空
        } // else结束
      } // 外层else结束

      for (RelNode rel : successors) { // 遍历所有候选节点
        if (operand.getRule() instanceof TransformationRule // 如果规则是转换规则
            && rel.getConvention() != previous.getConvention()) { // 且候选节点的约定与上一个节点不同
          continue; // 跳过该候选，转换规则要求约定一致
        } // if结束
        if (!operand.matches(rel)) { // 如果候选节点不匹配操作数
          continue; // 跳过该候选
        } // if结束
        if (ascending && operand.childPolicy != RelOptRuleOperandChildPolicy.UNORDERED) { // 如果是向上匹配且子节点策略不是无序的
          // We know that the previous operand was *a* child of its parent, // 注释：我们知道上一个操作数是其父节点的*一个*子节点
          // but now check that it is the *correct* child. // 注释：但现在检查它是否是*正确的*子节点
          if (previousOperand.ordinalInParent >= rel.getInputs().size()) { // 如果上一个操作数在父节点中的序号超出范围
            continue; // 跳过该候选
          } // if结束
          final RelSubset input = // 获取候选节点指定位置的输入子集
              (RelSubset) rel.getInput(previousOperand.ordinalInParent); 
          if (previousOperand.getMatchedClass() == RelSubset.class) { // 如果上一个操作数匹配RelSubset类
            // The matched subset (previous) should satisfy our input subset (input) // 注释：匹配的子集（previous）应该满足我们的输入子集（input）
            if (input.getSubsetsSatisfyingThis().noneMatch(previous::equals)) { // 如果输入子集的满足条件集合中不包含previous
              continue; // 跳过该候选
            } // if结束
          } else { // 如果上一个操作数不匹配RelSubset类
            if (!input.contains(previous)) { // 如果输入子集不包含上一个节点
              continue; // 跳过该候选
            } // if结束
          } // else结束
        } // if结束

        // Assign "childRels" if the operand is UNORDERED. // 注释：如果操作数是无序的，则设置childRels
        switch (parentOperand.childPolicy) { // 根据子节点策略进行不同的处理
        case UNORDERED: // 如果是无序策略
          // Note: below is ill-defined. Suppose there's a union with 3 inputs, // 注释：下面的实现是不完善的。假设有一个有3个输入的union
          // and the rule is written as Union.class, unordered(...) // 注释：规则写作 Union.class, unordered(...)
          // What should be provided for the rest 2 arguments? // 注释：其余2个参数应该提供什么？
          // RelSubsets? Random relations from those subsets? // 注释：RelSubsets？还是这些子集中的随机关系表达式？
          // For now, Calcite code does not use getChildRels, so the bug is just waiting its day // 注释：目前Calcite代码不使用getChildRels，所以这个bug只是在等待爆发
          if (ascending) { // 如果是向上匹配
            final List<RelNode> inputs = Lists.newArrayList(rel.getInputs()); // 获取候选节点的输入列表
            inputs.set(previousOperand.ordinalInParent, previous); // 将上一个节点设置到对应位置
            setChildRels(rel, inputs); // 设置候选节点的childRels
          } else { // 如果是向下匹配
            List<RelNode> inputs = getChildRels(previous); // 获取上一个节点的childRels
            if (inputs == null) { // 如果childRels为null
              inputs = Lists.newArrayList(previous.getInputs()); // 使用上一个节点的实际输入
            } // if结束
            inputs.set(operand.ordinalInParent, rel); // 将候选节点设置到对应位置
            setChildRels(previous, inputs); // 设置上一个节点的childRels
          } // else结束
          break; // 跳出switch
        default: // 默认情况
          break; // 不做任何处理
        } // switch结束

        rels[operandOrdinal] = rel; // 将候选节点绑定到操作数数组的对应位置
        matchRecurse(solve + 1); // 递归匹配下一个操作数
      } // for循环结束
    } // 外层else结束
  } // matchRecurse方法结束
} // 类定义结束
